create table public."Reviews" (
                                  id bigint generated by default as identity not null,
                                  created_at date not null,
                                  user_name text not null,
                                  rating smallint not null,
                                  title text not null,
                                  comment text not null,
                                  car_id bigint null,
                                  helpful_count bigint not null default '0'::bigint,
                                  constraint Reviews_pkey primary key (id),
                                  constraint Reviews_car_id_fkey foreign KEY (car_id) references "Car_Models" ("Model_ID") on update CASCADE on delete CASCADE,
                                  constraint Reviews_rating_check check (
                                      (
                                          (rating >= 1)
                                              and (rating <= 5)
                                          )
                                      )
) TABLESPACE pg_default;